const quizData = [
  {"question": "Assertion (A): Fixed costs remain constant over a period of time. Reason (R): Fixed costs do not change with the level of production.", "options": ["a) Both true & R explains A", "b) Both true but R not explain A", "c) A true R false", "d) A false R true"], "correct": "a) Both true & R explains A"},
  {"question": "Rent paid for a factory building is classified as which type of cost?", "options": ["a) Variable cost", "b) Operating cost", "c) Fixed cost", "d) Semi-variable cost"], "correct": "c) Fixed cost"},
  {"question": "Electricity charges based on usage are treated as which cost?", "options": ["a) Fixed cost", "b) Variable cost", "c) Sunk cost", "d) Capital cost"], "correct": "b) Variable cost"},
  {"question": "Which of the following is an operating cost?", "options": ["a) Raw material", "b) Labour wages", "c) Office supplies", "d) Packaging material"], "correct": "c) Office supplies"},
  {"question": "Which of the following is an example of semi-variable cost?", "options": ["a) Factory rent", "b) Direct raw material", "c) Telephone bill with fixed and usage charges", "d) Purchase of land"], "correct": "c) Telephone bill with fixed and usage charges"},
  {"question": "Contribution is mainly used to:", "options": ["a) Calculate tax", "b) Cover fixed cost and earn profit", "c) Increase variable cost", "d) Reduce selling price"], "correct": "b) Cover fixed cost and earn profit"},
  {"question": "When is the break-even point reached?", "options": ["a) Profit maximum", "b) Loss maximum", "c) Total cost = Total revenue", "d) Variable cost zero"], "correct": "c) Total cost = Total revenue"},
  {"question": "What does the break-even point indicate?", "options": ["a) Maximum sales", "b) Profit zone", "c) No profit, no loss", "d) Maximum loss"], "correct": "c) No profit, no loss"},
  {"question": "How is contribution per unit calculated?", "options": ["a) SP - Fixed cost", "b) Fixed - Variable cost", "c) SP - Variable cost", "d) Total cost - SP"], "correct": "c) SP - Variable cost"},
  {"question": "Given fixed cost 20,000, SP ₹50, VC ₹30, what is BEP (units)?", "options": ["a) 500", "b) 1000", "c) 1500", "d) 2000"], "correct": "b) 1000"},
  {"question": "If selling price increases while costs remain same, BEP will:", "options": ["a) Increase", "b) Decrease", "c) Remain same", "d) Become zero"], "correct": "b) Decrease"},
  {"question": "Which assumption is made in break-even analysis?", "options": ["a) Variable cost changes", "b) Multiple products sold", "c) Selling price constant", "d) Demand fluctuates"], "correct": "c) Selling price constant"},
  {"question": "A break-even chart shows the relationship between:", "options": ["a) Price & demand", "b) Profit & loss", "c) Cost, revenue & output", "d) Tax & income"], "correct": "c) Cost, revenue & output"},
  {"question": "Cash received from customers is treated as:", "options": ["a) Cash outflow", "b) Cash inflow", "c) Capital expenditure", "d) Operating loss"], "correct": "b) Cash inflow"},
  {"question": "Payment of salaries is classified as:", "options": ["a) Cash inflow", "b) Cash outflow", "c) Capital receipt", "d) Revenue inflow"], "correct": "b) Cash outflow"},
  {"question": "Purchase of machinery is classified under:", "options": ["a) Operating cash flow", "b) Investing cash flow", "c) Financing cash flow", "d) Revenue inflow"], "correct": "b) Investing cash flow"},
  {"question": "When does positive cash flow occur?", "options": ["a) Outflow > Inflow", "b) Inflow = Outflow", "c) Inflow > Outflow", "d) Cash is zero"], "correct": "c) Inflow > Outflow"},
  {"question": "Repayment of bank loan is treated as:", "options": ["a) Cash inflow", "b) Investing inflow", "c) Financing cash outflow", "d) Operating inflow"], "correct": "c) Financing cash outflow"},
  {"question": "Which activity improves cash flow?", "options": ["a) Delaying collections", "b) Increasing inventory", "c) Encouraging cash sales", "d) Excess borrowing"], "correct": "c) Encouraging cash sales"},
  {"question": "Cash flow projection mainly helps in:", "options": ["a) Ignoring expenses", "b) Planning future cash needs", "c) Reducing tax", "d) Fixing selling price"], "correct": "b) Planning future cash needs"},
  {"question": "The flow List inflows → List outflows → Net flow → Closing balance represents:", "options": ["a) Income statement", "b) Break-even analysis", "c) Cash flow projection", "d) Pricing method"], "correct": "c) Cash flow projection"},
  {"question": "What is one disadvantage of cash flow projection?", "options": ["a) Improves planning", "b) Helps budgeting", "c) Based on assumptions", "d) Identifies shortages"], "correct": "c) Based on assumptions"},
  {"question": "What does pricing refer to?", "options": ["a) Amount paid", "b) Process of fixing price", "c) Cost of production", "d) Profit calculation"], "correct": "b) Process of fixing price"},
  {"question": "Charging 99 instead of ₹100 is an example of:", "options": ["a) Cost-plus", "b) Skimming", "c) Psychological pricing", "d) Premium pricing"], "correct": "c) Psychological pricing"},
  {"question": "Setting a high initial price and reducing it later is called:", "options": ["a) Penetration", "b) Economy", "c) Skimming", "d) Competitive"], "correct": "c) Skimming"},
  {"question": "Penetration pricing is most suitable when:", "options": ["a) Product is luxury", "b) Market is highly competitive", "c) Demand is low", "d) Costs are very high"], "correct": "b) Market is highly competitive"},
  {"question": "Match the following pricing methods: A. Cost-plus pricing B. Competitive pricing C. Value-based pricing 1. Market price reference 2. Customer perception 3. Cost + margin", "options": ["a) A-1, B-2, C-3", "b) A-3, B-1, C-2", "c) A-2, B-3, C-1", "d) All incorrect"], "correct": "b) A-3, B-1, C-2"},
  {"question": "Which factor directly affects pricing?", "options": ["a) Employee skills", "b) Cost of production", "c) Office location", "d) Training"], "correct": "b) Cost of production"},
  {"question": "Government taxes affecting price are classified as:", "options": ["a) Internal factors", "b) External factors", "c) Cost factors", "d) Demand factors"], "correct": "b) External factors"},
  {"question": "Which external factor strongly affects pricing decisions?", "options": ["a) Production efficiency", "b) Government regulations", "c) Employee skills", "d) Internal policy"], "correct": "b) Government regulations"},
  {"question": "What does an income statement show?", "options": ["a) Assets & liabilities", "b) Cash flows", "c) Profit or loss", "d) Capital structure"], "correct": "c) Profit or loss"},
  {"question": "Gross profit is calculated as:", "options": ["a) Sales - Expenses", "b) Sales - COGS", "c) Revenue - Tax", "d) Income - Loss"], "correct": "b) Sales - COGS"},
  {"question": "Net profit is calculated after deducting:", "options": ["a) Only fixed costs", "b) Only variable costs", "c) All expenses from revenue", "d) GST only"], "correct": "c) All expenses from revenue"},
  {"question": "Single-step income statement calculates:", "options": ["a) Gross profit", "b) Operating profit", "c) Net income directly", "d) Contribution margin"], "correct": "c) Net income directly"},
  {"question": "Which expense is an operating expense?", "options": ["a) Raw material", "b) Rent", "c) Closing stock", "d) Sales revenue"], "correct": "b) Rent"},
  {"question": "Which financial statement shows revenue and expenses for a specific period?", "options": ["a) Balance sheet", "b) Cash book", "c) Income statement", "d) Ledger"], "correct": "c) Income statement"},
  {"question": "GST is classified as which type of tax?", "options": ["a) Direct", "b) Indirect", "c) Progressive", "d) Corporate"], "correct": "b) Indirect"},
  {"question": "GST is finally borne by whom?", "options": ["a) Manufacturer", "b) Wholesaler", "c) Retailer", "d) End consumer"], "correct": "d) End consumer"},
  {"question": "GST input tax credit allows businesses to:", "options": ["a) Pay double tax", "b) Avoid tax entirely", "c) Reduce tax burden on inputs", "d) Increase price"], "correct": "c) Reduce tax burden on inputs"},
  {"question": "Base price 1,000 with 18% GST gives final price of:", "options": ["a) 1080", "b) 1180", "c) 1200", "d) 1150"], "correct": "b) 1180"},
  {"question": "If milk is taxed at 0% GST, final price will be:", "options": ["a) Less than base", "b) Equal to base", "c) More than base", "d) Double"], "correct": "b) Equal to base"},
  {"question": "AC taxed at 28% GST mainly affects:", "options": ["a) Cost only", "b) Profit only", "c) Final selling price", "d) Quantity produced"], "correct": "c) Final selling price"},
  {"question": "A café sells 750 cups at 100 with cost 60. What is monthly gross profit?", "options": ["a) 15000", "b) 30000", "c) 45000", "d) 10000"], "correct": "b) 30000"},
  {"question": "With monthly rent 20,000 and contribution 40 per cup, BEP is:", "options": ["a) 250", "b) 500", "c) 750", "d) 1000"], "correct": "b) 500"},
  {"question": "If variable cost per unit decreases, contribution per unit will:", "options": ["a) Decrease", "b) Increase", "c) Remain same", "d) Become zero"], "correct": "b) Increase"},
  {"question": "How is unit cost calculated?", "options": ["a) Total cost × Units", "b) Total cost + Units", "c) Profit Units", "d) SP Units"], "correct": "b) Total cost + Units"},
  {"question": "Which pricing method focuses on customer perception?", "options": ["a) Cost-plus", "b) Competitive", "c) Value-based", "d) Economy"], "correct": "c) Value-based"},
  {"question": "Which pricing strategy helps quick market entry?", "options": ["a) Premium", "b) Skimming", "c) Penetration", "d) Psychological"], "correct": "c) Penetration"},
  {"question": "Negative cash flow indicates:", "options": ["a) Profit earned", "b) Cash shortage", "c) Increase in sales", "d) No expenses"], "correct": "b) Cash shortage"},
  {"question": "Income statement is generally prepared:", "options": ["a) Daily", "b) Weekly", "c) Periodically / Annually", "d) Hourly"], "correct": "c) Periodically / Annually"}
]
